// <auto-generated />
namespace Infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class HorarioExpediente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HorarioExpediente));
        
        string IMigrationMetadata.Id
        {
            get { return "201608182041514_HorarioExpediente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
